# sets the region so that application can be run outside of ec2 instance
cloud:
  aws:
    region:
      static: eu-west-1

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: my-json-queue
        input:
          destination: my-json-queue
          group: ala-ma-kota
      sqs:
        bindings:
          input:
            consumer:
              maxNumberOfMessages: 10
